# Generated by Django 5.0.2 on 2024-03-18 00:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("case_app", "0003_alter_case_lawyer_case_court_court_court_type"),
        ("user_app", "0002_remove_userprofile_user_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
