# Generated by Django 5.0.2 on 2024-03-18 00:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "client_app",
            "0002_remove_client_contact_information_client_address_and_more",
        ),
        ("invoice_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="adjustment_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="billing_period_end",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="invoice",
            name="billing_period_start",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="invoice",
            name="client",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="client_app.client",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="discount_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(default="INV-0002", max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_method",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SENT", "Sent"),
                    ("PAID", "Paid"),
                    ("OVERDUE", "Overdue"),
                ],
                default="DRAFT",
                max_length=50,
            ),
        ),
    ]
