# Generated by Django 5.0.3 on 2024-03-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "invoice_app",
            "0002_invoice_adjustment_amount_invoice_billing_period_end_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="description",
            field=models.CharField(default="Description", max_length=255),
        ),
    ]
