# Generated by Django 5.0.3 on 2024-03-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_app", "0003_alter_case_lawyer_case_court_court_court_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="end_date",
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name="case",
            name="start_date",
            field=models.DateField(default=None),
        ),
    ]
